### ISSUE TITLE
Can you give a complete example?

### ISSUE THREAD

**Issue by saycchai** [galikvalkin/react-native-form-validation#1]
Now the example given in the readme cannot run as something is missing (e.g. styles is not defined), can you give a complete example? Thx!

**Comment by galikvalkin** [comment]
@saycchai 
Hello. Updated example. Hope it will help.

**Comment by hungdev** [comment]
@galikvalkin where is the link for example?

**Comment by vedovato** [comment]
Examples working as expected, here. Can we close this?
