### ISSUE TITLE
Validation message

### ISSUE THREAD

**Issue by Gecco** [galikvalkin/react-native-form-validation#2]
Is there any option to display custom validation message in FormItem? 

This this.refs.form.validate() return a array of objects and I don't see how can I use it for display messages.

It will be good to have another function which return bool instead of array of objects.

**Comment by vgalkin** [comment]
@Gecco 
Hello.
Right now `validate` method returns list of objects. Each object contains field, called `isValid`. So if you have 3 `FormItem` components in `Form` and first is not valid, result of `validate` method will look like this:

`[{isValid: false,...}, {isValid: true,...}, {isValid: true,...}]`
