### ISSUE TITLE
error undefined is not an object

### ISSUE THREAD

**Issue by YasirSherzad** [galikvalkin/react-native-form-validation#3]
I receive this error and it kinda points to the line where I am importing `import { Form, FormItem } from 'react-native-form-validation'`

this is the error: `undefined is not an object (evaluating '_react.PropTypes.bool') `
I think this happening because the separation of PropTypes from react.

How to fix this! thanx

**Comment by vedovato** [comment]
Hello, i managed to fix it.
Just opened a PR, let's wait for @galikvalkin review and merge.

@YasirPanjsheri, you can try my fix now by pointing my repo in your package.json file
Hope it helps

**Comment by galikvalkin** [comment]
Hey guys, thank you for your involvement;

@vedovato 
Thank you for your help. I've seen your pull request. Unfortunately, it contains `node_modules` folder which is not a good option here. Sorry, I can not merge it.

@YasirPanjsheri 
I've changed dependencies in module. It should work now.
