### ISSUE TITLE
Undefined error when submitting

### ISSUE THREAD

**Issue by fithaN** [galikvalkin/react-native-form-validation#5]
I tried using the example as below.
<Form ref="form" shouldValidate={true}>
              <FormItem isRequired={true} regExp={/^\d+$/}>
                <TextInput
                  placeholder="Email address"
                  placeholderTextColor="#212121"
                  returnKeyType="next"
                  onSubmitEditing={() => this.passwordInput.focus()}
                  keyboardType="email-address"
                  autoCapitalize="none"
                  autoCorrect={false}
                  style={styles.input}
                  value={this.state.textInput1}
                  onChange={this.textInput1Change.bind(this)}
                />
              </FormItem>

              <FormItem isRequired={true}>
                <TextInput
                  placeholder="Password"
                  placeholderTextColor="#212121"
                  returnKeyType="go"
                  secureTextEntry
                  ref={input => (this.passwordInput = input)}
                  style={styles.input}
                />
              </FormItem>
            </Form>
But i am getting undefined error as attached when submitting the form.
<img width="292" alt="screen shot 2018-01-23 at 7 10 56 pm" src="https://user-images.githubusercontent.com/33620488/35264529-38f29656-0071-11e8-9fa1-c62a7813141b.png">

**Comment by galikvalkin** [comment]
Hello @fithaN 
Thank you for report.

Have you tried to setup `value` field for TextInput component?

As I can see from your example:


`<TextInput
              placeholder="Password"
              placeholderTextColor="#212121"
              returnKeyType="go"
              secureTextEntry
              ref={input => (this.passwordInput = input)}
              style={styles.input}
            />`

do not contain `value` field.
